### ISSUE TITLE
Potential bug in binary_operator

### ISSUE THREAD

**Issue by cnapun** [lucidrains/gateloop-transformer#2]
From my best reading of the paper, my understanding was that `a_j.real * kv_i + kv_j` should be `a_j * kv_i + kv_j` in `binary_operator`, and then in the output step, you take `kv.real`. In a few places there is the following code:
```
    def binary_operator(a, b):
        a_i, kv_i = a
        a_j, kv_j = b
        return a_j * a_i, a_j.real * kv_i + kv_j
```
but then in other places it's just  `return a_j * a_i, a_j * kv_i + kv_j`. I don't think these are equivalent (but maybe i'm wrong)

**Comment by lucidrains** [comment]
@cnapun ah shoot! they aren't equivalent, just tested it

let me rerun the experiment 🤞

**Comment by lucidrains** [comment]
hmm, still not seeing it

at least the implementation is now faithful. thanks!
